apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: 333456/client
          env:
            - name: NEXT_PUBLIC_STRIPE_PUBLISHER_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-publisher-key
                  key: NEXT_PUBLIC_STRIPE_PUBLISHER_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
